---
azure_resource_group: "{{ destination_resource_group }}"
azure_region: "{{ destination_region }}"
azure_number_vm: "{{ src_vm_info.vmss.0.sku.capacity }}"
azure_vm_image: "{{ src_vm_info.vmss.0.properties.virtualMachineProfile.storageProfile.imageReference }}"
azure_vm_size: "{{ src_vm_info.vmss.0.sku.name }}"
azure_load_balancer:
  domain_name: "{{ destination_resource_group | replace('_', '-') }}-{{ destination_region | replace('_', '-') }}-webapp1"
  name: "{{ source_resource_group }}-lb"
  public_ip_name: "{{ source_resource_group }}-lb-public-ipp"
  backend_address_pool: "{{ source_resource_group }}-vm-pool"
operation: create