---
- name: Delete resource group
  ansible.builtin.include_role:
    name: cloud.azure_ops.azure_manage_resource_group
  vars:
    azure_manage_resource_group_operation: delete
    azure_manage_resource_group_name: "{{ scale_virtual_machine_resource_group }}"
    azure_manage_resource_group_region: "{{ scale_virtual_machine_region }}"
    azure_manage_resource_group_force_delete_nonempty: true
