---
azure_network_interface:
  name: "{{ vm_name }}"
  vnet_name: "{{ vnet_info.virtualnetworks[0].name }}" # This is how the azure_rm_virtualmachine module creates its default network interface - using the first vnet
  subnet_name: "{{ vnet_info.virtualnetworks[0].subnets[0].name }}"
  ip_configurations:
    - name: default
      primary: true
      public_ip_address_name: "{{ vm_name }}"
      load_balancer_backend_address_pools: "{{ azure_vm.load_balancer_backend_address_pools | default(omit) }}"
